//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduateSoftware.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AdminGraduateVerification
    {
        public int VerificationID { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string AdminID { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "* A valid student id is required.")]
        [Display(Name = "Student ID")]
        public string StudentID { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "* A valid first name is required.")]
        [Display(Name = "First Name")]
        public string GraduateName { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "* A valid last name is required.")]
        [Display(Name = "Last Name")]
        public string GrauateSurname { get; set; }

        [Required]
        [StringLength(50)]
        [EmailAddress(ErrorMessage = "* A valid email address is required.")]
        [Display(Name = "Email")]
        public string GraduateEmail { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Graduate Graduate { get; set; }
    }
}
